In [2]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('../data/noaa_cdc_uscensus.csv')

# Display the first few rows to verify
print(df.shape)
df.head()

(14544, 54)

,year,stateabbr_c,statedesc_c,locationname_c,category_c,locationid_c,measure_c,data_value_c,low_confidence_limit_c,high_confidence_limit_c,...,pct_female_u,cbsa_code_u,median_household_income_u,pct_bachelors_plus_u,pct_graduate_degree_u,pct_less_than_hs_u,pct_white_u,pct_black_u,pct_hispanic_u,pct_asian_u
0,2014,AL,Alabama,Mobile,Health Outcomes,150000,Chronic obstructive pulmonary disease among ad...,8.7,8.5,8.8,...,52.1,33660.0,43844.0,6.7,13.2,4.5,58.4,34.9,2.6,1.9
1,2014,AL,Alabama,Tuscaloosa,Health Outcomes,177256,Chronic obstructive pulmonary disease among ad...,9.1,8.9,9.4,...,51.8,46220.0,43567.0,5.6,14.1,4.5,61.6,33.2,2.8,1.2
2,2014,AL,Alabama,Birmingham,Health Outcomes,107000,Chronic obstructive pulmonary disease among ad...,9.4,9.3,9.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2014,AL,Alabama,Montgomery,Health Outcomes,151000,Chronic obstructive pulmonary disease among ad...,8.6,8.5,8.8,...,52.0,33860.0,46977.0,6.2,16.0,5.2,50.5,43.0,3.1,1.7
4,2014,AL,Alabama,Huntsville,Health Outcomes,137000,Chronic obstructive pulmonary disease among ad...,7.5,7.4,7.7,...,50.7,26620.0,55881.0,6.9,22.7,3.8,68.2,21.5,4.9,2.2

# Pivoting the data

In [3]:
measure_specific = ['measureid_c', 'measure_c', 'data_value_c', 'low_confidence_limit_c',
                    'high_confidence_limit_c', 'category_c', 'categoryid_c', 'short_question_text_c']
index_cols = [c for c in df.columns if c not in measure_specific]

df_pivot = df.pivot(
    index=index_cols,
    columns='measureid_c',
    values='data_value_c'
).reset_index()

df_pivot.columns.name = None

print(df_pivot.shape)
df_pivot.head()

(1818, 54)

,year,stateabbr_c,statedesc_c,locationname_c,locationid_c,totalpopulation_c,geolocation_c,sca_release_id_c,msa_c,msa_code,...,pct_hispanic_u,pct_asian_u,CASTHMA,CHD,COPD,LPA,MHLTH,OBESITY,PHLTH,STROKE
0,2014,AK,Alaska,Anchorage,203000,"291,826","(61.149868731, -149.111113424)",2014_500_Cities_2016_release,"Anchorage, AK Metro Area",112.0,...,7.3,6.6,8.6,5.0,5.0,19.2,9.4,27.7,9.9,2.6
1,2014,AL,Alabama,Birmingham,107000,"212,237","(33.5275663773, -86.7988174678)",2014_500_Cities_2016_release,"Birmingham, AL Metro Area",136.0,...,NaN,NaN,11.4,7.6,9.4,31.7,17.0,39.0,18.3,5.0
2,2014,AL,Alabama,Huntsville,137000,"180,105","(34.6989692671, -86.6387042882)",2014_500_Cities_2016_release,"Huntsville, AL Metro Area",259.0,...,4.9,2.2,9.6,6.7,7.5,24.9,14.0,32.0,13.9,3.2
3,2014,AL,Alabama,Mobile,150000,"195,111","(30.6776248648, -88.1184482714)",2014_500_Cities_2016_release,"Mobile, AL Metro Area",333.0,...,2.6,1.9,10.7,7.6,8.7,27.4,15.8,37.6,16.3,4.1
4,2014,AL,Alabama,Montgomery,151000,"205,764","(32.3472645333, -86.2677059552)",2014_500_Cities_2016_release,"Montgomery, AL Metro Area",337.0,...,3.1,1.7,10.8,7.2,8.6,27.9,15.5,36.8,16.2,4.1

# Exploratory Analysis

In [5]:
#Year-wise country-wise data

df.groupby(['year', 'statedesc_c']).size().unstack(fill_value=0)

statedesc_c,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Florida,Georgia,Hawaii,...,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
year,,,,,,,,,,,,,,,,,,,,,
2014,40,8,24,24,160,48,32,88,48,8,...,8,16,176,32,8,24,32,8,48,8
2015,40,8,24,24,160,48,32,88,48,8,...,8,16,176,32,8,24,32,8,48,8
2016,40,8,24,24,160,48,32,88,48,8,...,8,16,176,32,8,24,32,8,48,8
2017,40,8,24,24,160,48,32,88,48,8,...,8,16,176,32,8,24,32,8,48,8
2018,40,8,24,24,160,48,32,88,32,0,...,8,8,176,32,8,24,32,8,48,8
2019,40,8,24,24,160,48,32,88,32,0,...,8,8,176,32,8,24,32,8,48,8
2020,40,8,24,24,160,48,32,88,32,0,...,8,8,176,32,8,24,32,8,48,8
2021,40,8,24,24,160,48,32,0,32,0,...,8,8,176,32,8,24,32,8,48,8
2022,40,8,24,24,160,48,32,88,32,0,...,8,8,176,32,8,24,32,8,48,8
2023,40,8,24,24,160,48,32,88,32,0,...,8,8,176,32,8,24,32,8,48,8

In [ ]:
#Missing Values
missing = df.isnull().mean().mul(100).round(2).sort_values(ascending=False)
print(missing[missing > 0])  # only show columns that actually have missing values

tsun_n                       99.83
pct_asian_u                  16.17
median_household_income_u    16.17
msa_u                        16.17
total_population_u           16.17
median_age_u                 16.17
pct_male_u                   16.17
cbsa_code_u                  16.17
pct_female_u                 16.17
pct_bachelors_plus_u         16.17
pct_graduate_degree_u        16.17
pct_less_than_hs_u           16.17
pct_white_u                  16.17
pct_black_u                  16.17
pct_hispanic_u               16.17
cldd_n                        7.54
tavg_n                        7.43
htdd_n                        7.43
tmin_n                        6.99
emnt_n                        6.99
dt00_n                        6.99
dt32_n                        6.99
emxt_n                        6.93
dx90_n                        6.93
tmax_n                        6.93
dx32_n                        6.93
dx70_n                        6.93
prcp_n                        4.24
msa_n                         1.49
longitude_n                   1.49
latitude_n                    1.49
name_n                        1.49
dtype: float64